### ISSUE TITLE
what is ext command in instructions?

### ISSUE THREAD

**Issue by nikivdev** [fabiospampinato/vscode-open-in-finder#2]

**Comment by fabiospampinato** [comment]
I'm sorry, I didn't understand what you mean.

Is something missing in the readme?

**Comment by nikivdev** [comment]
In install instructions you have `ext install vscode-open-in-finder` but what is this ext command as it doesn't come bundled with VS Code. :)

**Comment by fabiospampinato** [comment]
I'm not sure where it is documented, but if you do:
1. `cmd+P`
2. `ext install vscode-open-in-finder`
3. `enter`

The extensions panel will be opened with `vscode-open-in-finder` written in the search bar.
