### ISSUE TITLE
Can you be able to use it when viewing PDFs or other non-text files?

### ISSUE THREAD

**Issue by jmhammond** [fabiospampinato/vscode-open-in-finder#6]
Excellent extension! This is almost exactly what I needed for my workflow of writing latex files, compiling PDFs, and then opening in my external editor for printing (for some reason VS Code's PDF viewer doesn't support printing?!)

Right now I'm using "Open in Finder" to load my tex file in Finder and scrolling down to the PDF.  

Can it be implemented to run directly from a PDF 'preview editor'?  When I run the command with the PDF in my current editor, it open loads the project root.

**Comment by jmhammond** [comment]
Looking into it, I'm thinking maybe you can't.  I don't know anything about writing VS Code extensions, but when I turned on logging for the window (under Show Logs > Window), I get this:

...
2023-04-19 10:44:36.418 [trace] [DEBOUNCE: Links] for file:///Users/john/Nextcloud/Documents/math242/dailies/6.2.tex is 1000ms
2023-04-19 10:44:36.418 [debug] Webview(daf1c0f9-87cb-4bac-be2f-cfd74bab62d8): webview ready
...

So I think the webview is viewing the PDF, but you're not given the filename from the window. I bet the filename is [buried inside the WebView HTML itself.](https://code.visualstudio.com/api/references/vscode-api#Webview).

I'm going to leave this open in the off-chance you have a better idea than me, but I'm guessing "not feasible, sorry" is the answer.  Thanks for your time!

**Comment by fabiospampinato** [comment]
Check out this other extension of mine, I think it should address your problem: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-application

**Comment by jmhammond** [comment]
This is really neat. Thanks!
